### ISSUE TITLE
SYSSE.bin and SNR extractor/decompiler not working

### ISSUE THREAD

**Issue by StevenBeach33** [DCNick3/ShinDataUtil#10] opened 2024-10-29 19:35 UTC
I tried to extract/decompile sysse.bin and snr files from konosuba game switch, but it not working

SYSSE.bin : 
```
D:\PC\ShinDataUtil-konosuba>dotnet run sysse-extract sysse.bin sys
Process terminated. Assertion Failed
   at ShinDataUtil.Decompression.ShinSysseExtractor.Extract(ReadOnlySpan`1 data,
 String destinationDirectory) in D:\PC\ShinDataUtil-konosuba\Decompression\ShinS
ysseExtractor.cs:line 140
   at ShinDataUtil.Program.SysseExtract(ReadOnlyMemory`1 syssedata, String _, St
ring outname) in D:\PC\ShinDataUtil-konosuba\Program.cs:line 350
   at ShinDataUtil.Program.ActionList.<>c__DisplayClass7_0.<AddSingleFileProcess
ingAction>b__0(ReadOnlySpan`1 args) in D:\PC\ShinDataUtil-konosuba\Program.cs:li
ne 654
   at ShinDataUtil.Program.ActionList.Execute(String actionname, ReadOnlySpan`1
args) in D:\PC\ShinDataUtil-konosuba\Program.cs:line 683
   at ShinDataUtil.Program.MainWrap(String[] args) in D:\PC\ShinDataUtil-konosub
a\Program.cs:line 720
   at ShinDataUtil.Program.Main(String[] args) in D:\PC\ShinDataUtil-konosuba\Pr
ogram.cs:line 727
```
SNR : 
```

D:\PC\ShinDataUtil-konosuba>dotnet run scenario-decompile main.snr main
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part
 of the path 'D:\PC\ShinDataUtil-konosuba\main\head_data.json'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share,
FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append
, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at ShinDataUtil.Decompression.Scenario.ShinScenarioDecompiler.Decompile(ReadO
nlyMemory`1 memory, String destinationDirectory) in D:\PC\ShinDataUtil-konosuba\
Decompression\Scenario\ShinScenarioDecompiler.cs:line 332
   at ShinDataUtil.Program.ScenarioDecompile(ReadOnlyMemory`1 snrdata, String _,
 String outname) in D:\PC\ShinDataUtil-konosuba\Program.cs:line 377
   at ShinDataUtil.Program.ActionList.<>c__DisplayClass7_0.<AddSingleFileProcess
ingAction>b__0(ReadOnlySpan`1 args) in D:\PC\ShinDataUtil-konosuba\Program.cs:li
ne 654
   at ShinDataUtil.Program.ActionList.Execute(String actionname, ReadOnlySpan`1
args) in D:\PC\ShinDataUtil-konosuba\Program.cs:line 683
   at ShinDataUtil.Program.MainWrap(String[] args) in D:\PC\ShinDataUtil-konosub
a\Program.cs:line 720
   at ShinDataUtil.Program.Main(String[] args) in D:\PC\ShinDataUtil-konosuba\Pr
ogram.cs:line 727
```

For tex-decode and txpl-extract seems not work in a few files

**Comment by DCNick3** [comment] 2024-11-04 07:33
Regarding `SYSSE`, it's just unsupported, as far as I remember. The team working on translation didn't need it, so I never implemented support of se for konosuba. Do you want it supported?

Regarding scenario, I believe the problem is that the directory you are telling it to extract into does not exist. The tool could've been smarter and created the directory for you, but alas, it doesn't. Sorry for that.

And, just to be sure, are you using it on the __first__ konosuba using shin (`この素晴らしい世界に祝福を！～希望の迷宮と集いし冒険者たち～Plus`, title id `01004920105FC000`)?

If you need tooling for the sequel (`この素晴らしい世界に祝福を！～呪いの遺物と惑いし冒険者たち～`, title id `010048F0179E6000`), look at [this fork](https://github.com/nikvoid/ShinDataUtil/tree/konosuba2) (branch `konosuba2`), it should have some support.

**Comment by StevenBeach33** [comment] 2024-11-04 08:41
> Regarding `SYSSE`, it's just unsupported, as far as I remember. The team working on translation didn't need it, so I never implemented support of se for konosuba. Do you want it supported?
> 
> Regarding scenario, I believe the problem is that the directory you are telling it to extract into does not exist. The tool could've been smarter and created the directory for you, but alas, it doesn't. Sorry for that.
> 
> And, just to be sure, are you using it on the **first** konosuba using shin (`この素晴らしい世界に祝福を！～希望の迷宮と集いし冒険者たち～Plus`, title id `01004920105FC000`)?
> 
> If you need tooling for the sequel (`この素晴らしい世界に祝福を！～呪いの遺物と惑いし冒険者たち～`, title id `010048F0179E6000`), look at [this fork](https://github.com/nikvoid/ShinDataUtil/tree/konosuba2) (branch `konosuba2`), it should have some support.

I see
What's inside SE files? 
And if possible, can you add support with ddz, imf, biz, anm, and dds files? I want to know what's inside there files.

Yes, i working in **first** one
I want to translating this game :)

Oh one more, i don't know why tex-decode can't decode all files in-game, just a few files can be decode, the error is like:
![Screenshot_20241030-022817](https://github.com/user-attachments/assets/b8ee3388-81b2-4ec8-a22a-b896acb447bc)

**Comment by masagrator** [comment] 2024-11-04 12:55
sysse - SYStem Sound Effects

**Comment by StevenBeach33** [comment] 2024-11-04 14:36
> sysse - SYStem Sound Effects

I see, it seems no need for translating

**Comment by DCNick3** [comment] 2024-11-04 20:30
> And if possible, can you add support with ddz, imf, biz, anm, and dds files?

These filetypes are not specific to the shin engine, so I am not really an expert on those. (konosuba is actually a chimera made out of shin for dialogues and its own(?) engine for the dungeon crawling parts). 

However, from the work of the other team translating konosuba (cc @nikvoid), I _think_ meddling with those files might not be needed for the translation.

> Oh one more, i don't know why tex-decode can't decode all files in-game, just a few files can be decode

I think I've found what the problem is. I've pushed a fix, which allows me to decode all .tex files in konosuba without errors

**Comment by nikvoid** [comment] 2024-11-04 20:54
I believe that for text translation you really only need SNR file + bunch of on-screen display texts that are null-terminated strings *embedded in NX main binary*, which is the pain in ass, because you either need to fit your translation in existing storage or use dynamic hooks in right places (which requires exploring game binary to some extent). Also there are some strings being moved not by `memcpy`, but in SIMD registers...

**Comment by nikvoid** [comment] 2024-11-04 21:36
@StevenBeach33 
SNR may throw errors because that `main` folder does not exist yet (It may look like bug/missed feature: scenario-decompile does not create it automatically)

About mentioned formats: 
- **DDS** are directx textures (**YES, Actually**) and you can open them with e.g. GIMP. 
- **DDZ** are LZLR-encoded DDS, if I recall correctly (use `lzlr-compress/decompress` subcommand of ShinDataUtil)
- **BIZ** are probably dungeon-crawler item, monsters, etc. databases
- **IMF** are probably 3d object meshes

**Comment by StevenBeach33** [comment] 2024-11-05 08:22
> > And if possible, can you add support with ddz, imf, biz, anm, and dds files?
> 
> These filetypes are not specific to the shin engine, so I am not really an expert on those. (konosuba is actually a chimera made out of shin for dialogues and its own(?) engine for the dungeon crawling parts).
> 
> However, from the work of the other team translating konosuba (cc @nikvoid), I _think_ meddling with those files might not be needed for the translation.
> 
> > Oh one more, i don't know why tex-decode can't decode all files in-game, just a few files can be decode
> 
> I think I've found what the problem is. I've pushed a fix, which allows me to decode all .tex files in konosuba without errors

I see. Thanks for fixing it.


> @StevenBeach33 SNR may throw errors because that `main` folder does not exist yet (It may look like bug/missed feature: scenario-decompile does not create it automatically)
> 
> About mentioned formats:
> 
> * **DDS** are directx textures (**YES, Actually**) and you can open them with e.g. GIMP.
> * **DDZ** are LZLR-encoded DDS, if I recall correctly (use `lzlr-compress/decompress` subcommand of ShinDataUtil)
> * **BIZ** are probably dungeon-crawler item, monsters, etc. databases
> * **IMF** are probably 3d object meshes

Thanks for explain it👍
I will be translating as best as i can

**Closed as completed** 2024-11-19 17:25 UTC
